apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/RSO-21/dev-stack.git
    targetRevision: main
    path: charts/monitoring
    helm:
      # IMPORTANT: kube-prometheus-stack ships big CRDs; we do NOT let Argo manage them
      skipCrds: true
      valueFiles:
        - ../../apps/shared/monitoring-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # These two frequently cause CRD patch/annotation-size issues. Remove them.
      # - ServerSideApply=true
      # - Replace=true
      - SkipDryRunOnMissingResource=true

  # IMPORTANT: CRDs are cluster-scoped and huge; ignore their diffs/annotations to avoid 262144 annotation limit
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations
