ingress:
  host: api.fri-food.4.165.160.2.nip.io
  tls:
    enabled: true
    issuer: letsencrypt-prod

ingressHosts:
  enabled: true
  hosts:
    frontend: fri-food.4.165.160.2.nip.io
  tls:
    enabled: true
    issuer: letsencrypt-prod



services:
  partner-service:
    image: frifoodacr.azurecr.io/partner-service:2896842

secrets:
  postgres:
    existingSecret: fri-food-postgres