apiVersion: v2
name: loki
description: Wrapper chart to deploy Loki + Promtail for cluster log aggregation
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: loki
    version: ">=5.0.0 <7.0.0"
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: ">=6.0.0 <7.0.0"
    repository: https://grafana.github.io/helm-charts
