{{- if .Values.ingressHosts.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fri-food-ms-hosts
  annotations:
    {{- if and .Values.ingressHosts.tls.enabled .Values.ingressHosts.tls.issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingressHosts.tls.issuer | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingressHosts.tls.enabled }}
  tls:
    - secretName: fri-food-ms-hosts-tls
      hosts:
        {{- with .Values.ingressHosts.hosts }}
        {{- if .users }}          - {{ .users | quote }}{{- end }}
        {{- if .auth }}           - {{ .auth | quote }}{{- end }}
        {{- if .orders }}         - {{ .orders | quote }}{{- end }}
        {{- if .payments }}       - {{ .payments | quote }}{{- end }}
        {{- if .offers }}         - {{ .offers | quote }}{{- end }}
        {{- if .partners }}       - {{ .partners | quote }}{{- end }}
        {{- if .notifications }}  - {{ .notifications | quote }}{{- end }}
        {{- if .frontend }}       - {{ .frontend | quote }}{{- end }}
        {{- end }}
  {{- end }}
  rules:
    {{- with .Values.ingressHosts.hosts }}

    {{- if .users }}
    - host: {{ .users | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 8000
    {{- end }}

    {{- if .auth }}
    - host: {{ .auth | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 8000
    {{- end }}

    {{- if .orders }}
    - host: {{ .orders | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 8000
    {{- end }}

    {{- if .payments }}
    - host: {{ .payments | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8000
    {{- end }}

    {{- if .offers }}
    - host: {{ .offers | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: offer-service
                port:
                  number: 8000
    {{- end }}

    {{- if .partners }}
    - host: {{ .partners | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: partner-service
                port:
                  number: 8000
    {{- end }}

    {{- if .notifications }}
    - host: {{ .notifications | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8000
    {{- end }}

    {{- if .frontend }}
    - host: {{ .frontend | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frifood-frontend
                port:
                  number: 80
    {{- end }}

    {{- end }}
{{- end }}
