ingress:
  host: api.fri-food-dev.68.210.120.104.nip.io

ingressHosts:
  enabled: true
  hosts:
    auth: auth-dev.68.210.120.104.nip.io
    users: users-dev.68.210.120.104.nip.io
    orders: orders-dev.68.210.120.104.nip.io
    payments: payments-dev.68.210.120.104.nip.io
    offers: offers-dev.68.210.120.104.nip.io
    partners: partners-dev.68.210.120.104.nip.io
    frontend: fri-food-dev.68.210.120.104.nip.io
    notifications: notifications-dev.68.210.120.104.nip.io

services:
  user-service:
    image: rsofrifoodacr.azurecr.io/user-service:dev
  order-service:
    image: rsofrifoodacr.azurecr.io/order-service:dev
  offer-service:
    image: rsofrifoodacr.azurecr.io/offer-service:dev
  auth-service:
    image: rsofrifoodacr.azurecr.io/auth-service:dev
  payment-service:
    image: rsofrifoodacr.azurecr.io/payment-service:dev
  api-gateway:
    image: rsofrifoodacr.azurecr.io/api-gateway:dev
  payment-grpc:
    image: rsofrifoodacr.azurecr.io/payment-service:dev
  notification-service:
    image: rsofrifoodacr.azurecr.io/notification-service:dev
  notification-consumer:
    image: rsofrifoodacr.azurecr.io/notification-service:dev
  frifood-frontend:
    image: rsofrifoodacr.azurecr.io/frifood-frontend:dev

secrets:
  postgres:
    existingSecret: fri-food-postgres